### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by marl64** [marl64/autoMP#1]
- [x] fill full canvas
- [x] create separate user-editable config file
- [x] add palette options
- [x] add dither option
- [x] add vertical centering
- [x] add option to stretch or zoom to fill canvas
- [x] add mario paint template to preview image
- [x] add fill function for optimising most common colour
- [x] add a GUI
- [ ] add palette white skip (ie use canvas white)
- [ ] add colour fill option for images that don't fill the frame
- [ ] look into options for how to handle transparency in input image
- [ ] fix cursor movement zigzag for speed
- [ ] mute snes9x while drawing; resume music when finished
- [ ] clean up colour and palette section
- [ ] cleanup path/filename code for loading and saving
- [ ] rename variables for clarity and consistency

**Comment by The-G-Zone** [comment]
- [ ] look into transparency options

**Comment by The-G-Zone** [comment]
- [ ] look into positional zoom/crop (top, bottom, side edges)
- [x] look into lightening/darkening settings
- [ ] have the cursor navigate to the main color page when done drawing
